/**
 * Generate docs/state.md for sanna-openclaw.
 *
 * Reads sources of truth and writes a deterministic state document.
 * Never hand-edit docs/state.md — regenerate with this script.
 *
 * Usage:
 *   npx tsx tools/generate-state-doc.ts          # regenerate docs/state.md
 *   npx tsx tools/generate-state-doc.ts --check  # exit 1 if docs/state.md is stale
 */

import { execSync } from 'node:child_process';
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { join } from 'node:path';

function repoRoot(): string {
  return execSync('git rev-parse --show-toplevel', { encoding: 'utf8' }).trim();
}

function gitSha(root: string): string {
  try {
    return execSync('git rev-parse HEAD', { cwd: root, encoding: 'utf8' }).trim().slice(0, 12);
  } catch {
    return 'unknown';
  }
}

function getVersion(root: string): string {
  const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8')) as Record<string, unknown>;
  return typeof pkg.version === 'string' ? pkg.version : '(unknown)';
}

function getSourceLayout(root: string): string {
  try {
    const output = execSync('git ls-files src/', { cwd: root, encoding: 'utf8' }).trim();
    if (!output) return '(empty)';
    const prefix = 'src/';
    const items = new Set<string>();
    for (const f of output.split('\n')) {
      const rel = f.startsWith(prefix) ? f.slice(prefix.length) : f;
      if (!rel) continue;
      const parts = rel.split('/');
      items.add(parts.length > 1 ? parts[0] + '/' : parts[0]);
    }
    const dirs = [...items].filter(i => i.endsWith('/')).sort();
    const files = [...items].filter(i => !i.endsWith('/')).sort();
    return [...dirs, ...files].map(i => `  ${i}`).join('\n');
  } catch {
    return '(unavailable)';
  }
}

function countTestFiles(root: string): number {
  try {
    const output = execSync('git ls-files tests/', { cwd: root, encoding: 'utf8' }).trim();
    if (!output) return 0;
    return output.split('\n').filter(f => f.endsWith('.test.ts') || f.endsWith('.spec.ts')).length;
  } catch {
    return 0;
  }
}

function getProductionDeps(root: string): string[] {
  const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8')) as Record<string, unknown>;
  const deps = (pkg.dependencies ?? {}) as Record<string, string>;
  return Object.entries(deps).map(([name, ver]) => `${name}: ${ver}`);
}

function getLatestChangelog(root: string): string {
  const path = join(root, 'CHANGELOG.md');
  if (!existsSync(path)) return '(no CHANGELOG.md)';
  const lines = readFileSync(path, 'utf8').split('\n');
  const entry: string[] = [];
  let inEntry = false;
  for (const line of lines) {
    if (line.startsWith('## ')) {
      if (inEntry) break;
      inEntry = true;
    }
    if (inEntry) entry.push(line);
    if (entry.length >= 10) break;
  }
  return entry.length ? entry.join('\n') : '(no entries found)';
}

function generateBody(root: string): string {
  const version = getVersion(root);
  const sourceLayout = getSourceLayout(root);
  const testCount = countTestFiles(root);
  const deps = getProductionDeps(root);
  const changelog = getLatestChangelog(root);

  const sections = [
    '# @sanna-ai/openclaw — State',
    '',
    '## Version',
    '',
    version,
    '',
    '## Source Layout (`src/`)',
    '',
    '```',
    sourceLayout,
    '```',
    '',
    '## Test Files',
    '',
    `Count: ${testCount} (\`tests/*.test.ts\`)`,
    '',
    '## Production Dependencies (`package.json`)',
    '',
    '```',
    ...deps,
    '```',
    '',
    '## Latest CHANGELOG Entry',
    '',
    changelog,
    '',
  ];
  return sections.join('\n');
}

function generateFull(root: string, sha: string, timestamp: string): string {
  const header = [
    `<!-- auto-generated by tools/generate-state-doc.ts — do not edit manually -->`,
    `<!-- generated: ${timestamp}  git-sha: ${sha} -->`,
    '',
    '',
  ].join('\n');
  return header + generateBody(root);
}

function comparable(content: string): string {
  return content
    .split('\n')
    .filter(l => !l.startsWith('<!-- generated:'))
    .join('\n')
    .trim();
}

function isoTimestamp(): string {
  return new Date().toISOString().replace(/\.\d{3}Z$/, 'Z');
}

function main(): void {
  const checkMode = process.argv.includes('--check');
  const root = repoRoot();
  const statePath = join(root, 'docs', 'state.md');

  if (checkMode) {
    if (!existsSync(statePath)) {
      process.stderr.write('ERROR: docs/state.md does not exist.\nRun: npx tsx tools/generate-state-doc.ts\n');
      process.exit(1);
    }
    const current = readFileSync(statePath, 'utf8');
    const sha = gitSha(root);
    const timestamp = isoTimestamp();
    const fresh = generateFull(root, sha, timestamp);

    if (comparable(current) === comparable(fresh)) {
      process.stdout.write('docs/state.md is up to date.\n');
      process.exit(0);
    }

    process.stderr.write('ERROR: docs/state.md is stale. Regenerate with:\n  npx tsx tools/generate-state-doc.ts\n\n');
    const currentLines = comparable(current).split('\n');
    const freshLines = comparable(fresh).split('\n');
    const maxLines = Math.max(currentLines.length, freshLines.length);
    let shown = 0;
    for (let i = 0; i < maxLines && shown < 40; i++) {
      const a = currentLines[i] ?? '';
      const b = freshLines[i] ?? '';
      if (a !== b) {
        process.stderr.write(`- ${a}\n+ ${b}\n`);
        shown++;
      }
    }
    process.exit(1);
  } else {
    const sha = gitSha(root);
    const timestamp = isoTimestamp();
    const content = generateFull(root, sha, timestamp);
    mkdirSync(join(root, 'docs'), { recursive: true });
    writeFileSync(statePath, content, 'utf8');
    process.stdout.write(
      `Generated docs/state.md (sha=${sha}, tests=${countTestFiles(root)}, version=${getVersion(root)})\n`
    );
  }
}

main();
